### ISSUE TITLE
Error after clone & start

### ISSUE THREAD

**Issue by SeLub** [rbiedrawa/react-redux-rtk-saga-mui-typescript-starter#1]
Hi,
Here what i did:
```
git clone ...,
npm i,
npm run start
```
**Result:**

Failed to compile.

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './runtime.js' is not defined by "exports" in /home/user/Documents/progs/react_boiler/react-redux-rtk-saga-mui-typescript-starter/node_modules/react-refresh/package.json
asset static/js/bundle.js 313 KiB [emitted] (name: main) 1 related asset
asset index.html 658 bytes [emitted]
asset asset-manifest.json 190 bytes [emitted]
runtime modules 28.2 KiB 13 modules
modules by path ./node_modules/core-js-pure/ 24.8 KiB 53 modules
modules by path ./node_modules/webpack-dev-server/client/ 62.1 KiB 12 modules
modules by path ./node_modules/webpack/hot/*.js 4.4 KiB
  ./node_modules/webpack/hot/dev-server.js 1.63 KiB [built] [code generated]
  ./node_modules/webpack/hot/log.js 1.37 KiB [built] [code generated]
  + 2 modules
modules by path ./node_modules/html-entities/lib/*.js 115 KiB
  ./node_modules/html-entities/lib/index.js 6.83 KiB [built] [code generated]
  ./node_modules/html-entities/lib/named-references.js 107 KiB [built] [code generated]
  + 2 modules
./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js 849 bytes [built] [code generated]
./src/index.tsx 39 bytes [not cacheable] [built] [code generated] [1 error]
./node_modules/ansi-html-community/index.js 4.26 KiB [built] [code generated]
./node_modules/events/events.js 14 KiB [built] [code generated]

ERROR in ./src/index.tsx
Module build failed (from ./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './runtime.js' is not defined by "exports" in /home/user/Documents/progs/react_boiler/react-redux-rtk-saga-mui-typescript-starter/node_modules/react-refresh/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:440:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:692:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at Object.<anonymous> (/home/user/Documents/progs/react_boiler/react-redux-rtk-saga-mui-typescript-starter/node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js:20:4)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)

ERROR in ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js 4:23-58
Module not found: Error: Package path ./runtime.js is not exported from package /home/user/Documents/progs/react_boiler/react-redux-rtk-saga-mui-typescript-starter/node_modules/react-refresh (see exports field in /home/user/Documents/progs/react_boiler/react-redux-rtk-saga-mui-typescript-starter/node_modules/react-refresh/package.json)

webpack 5.70.0 compiled with 2 errors in 11334 ms

**Comment by rbiedrawa** [comment]
Hi,

Unfortunately, I'm not using npm as a main package manager in this repo, but from Your logs:
```shell
.....
Package path ./runtime.js is not exported from package
.....
node_modules/react-refresh/package.json
.....
```

I think there is some compatibility issue between newest react-refresh:0.12.0 (release 12 days ago) and current webpack version😐

In order to fix this You may try to downgrade react-refresh and use version used in [yarn.lock](https://github.com/rbiedrawa/react-redux-rtk-saga-mui-typescript-starter/blob/main/yarn.lock#L14935), so:

`npm i react-refresh@0.11.0 --save --save-exact`

But better approach is just to use yarn as a main package manager together with provided [yarn.lock](https://github.com/rbiedrawa/react-redux-rtk-saga-mui-typescript-starter/blob/main/yarn.lock), so this will ensure that all installed dependencies are locked to specific version and every installation result in the exact same file structure in node_modules across all machines😉

For instruction how to install/use yarn pls follow [installation steps](https://github.com/rbiedrawa/react-redux-rtk-saga-mui-typescript-starter#installation) and [prerequisites yarn](https://github.com/rbiedrawa/react-redux-rtk-saga-mui-typescript-starter#prerequisites).

I hope this helps🙂

Cheers,
